name: Update settings

on:
  pull_request:
    branches:
      - main
    paths:
      - 'plugin.py'

jobs:
  check-settings:
    uses: sublimelsp/workflows/.github/workflows/changed-settings.yaml@v2
    with:
      version_file: 'plugin.py'
      version_regexp: 'TAG = "([^"]+)"'
